### ISSUE TITLE
Create a Discord server

### ISSUE THREAD

**Issue by MorganLmd** [Commit-based-Distribution/commit-based-distribution#15]
At least:

- 1 channel for public discussions
- 1 channel for team's discussions

**Comment by mderoullers** [comment]
@MorganLmd could you add the link in the issue if it's done please ?

**Comment by MorganLmd** [comment]
https://discord.gg/CC4MYUnXw4

**Comment by MorganLmd** [comment]
@mderoullers We will add it to the readme file when we write it.
