### ISSUE TITLE
Choose a language for the project

### ISSUE THREAD

**Issue by MorganLmd** [Commit-based-Distribution/commit-based-distribution#17]
For now, **Rust** and **Go** are the two competing languages. We have to choose one of them keeping in mind the following elements:
- Testing tools
- Learning curve
- Community
- Git library
- Relevance
- Any other element you want to highlight

**Comment by mderoullers** [comment]
We have to check if there are a Github and Gitlab client available for the language.

**Comment by MorganLmd** [comment]
Rust!
